# Generated by Django 5.0.3 on 2024-04-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients_recipe_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='recipe_step',
        ),
    ]
