# Generated by Django 5.0.3 on 2024-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_category_remove_recipe_category_recipe_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
