# Generated by Django 5.0.3 on 2024-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_nutritions_recipe_recipe_nutritions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_nutritions',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='recipe_nutritions',
            name='recipe',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Nutritions',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Recipe_Nutritions',
        ),
    ]
