# Generated by Django 5.0.3 on 2024-04-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_recipe_nutritions_nutrient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nutriens',
            new_name='Nutrients',
        ),
        migrations.RenameModel(
            old_name='Product_Nutriens',
            new_name='Product_Nutrients',
        ),
    ]
