# Generated by Django 5.0.3 on 2024-04-08 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_favorite_recipe'),
        ('products', '0007_remove_recipe_nutritions_nutrient_and_more'),
        ('recipes', '0006_category_remove_recipe_category_recipe_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'product', 'recipe')},
        ),
    ]
