# Generated by Django 5.0.3 on 2024-04-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_userweighthistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweighthistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
