# Generated by Django 5.0.3 on 2024-05-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_not_favorite'),
        ('Profile', '0006_alter_userweighthistory_date'),
    ]

    operations = [
    ]
