# Generated by Django 5.0.3 on 2024-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_merge_20240504_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='basic_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gold_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_plan',
            field=models.BooleanField(default=False),
        ),
    ]
