# Generated by Django 5.0.3 on 2024-05-11 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ration.ration_basic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_basic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
