# Generated by Django 5.0.3 on 2024-05-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_alter_profile_basic_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile_basic',
            unique_together=set(),
        ),
    ]
